name: ${name}
description: ${description}
authors:
  - srnyx
website: https://srnyx.com

main: ${group}.majesticmaterials.MajesticMaterials
version: ${version}
api-version: 1.13

commands:
  majesticreload:
    description: Reloads the plugin's configuration
    aliases:
      - mmreload
      - majesticmaterialsreload
    permission: majestic.reload

permissions:
  majestic.reload:
    description: Allows the player to use /majesticreload
  majestic.use:
    default: true
    description: Allows the player to get effects from eating configured food
